apiVersion: v1
kind: Namespace
metadata:
  name: aws-cicd

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJiaGFnaTk5IiwicGFzc3dvcmQiOiJkY2tyX3BhdF9tLXhGNDRnUjFiN0xUMTdLc2xtd2dtUHVKZEUiLCJlbWFpbCI6ImJoYWdpLnJhbWFoYWxsYUBnbWFpbC5jb20iLCJhdXRoIjoiWW1oaFoyazVPVHBrWTJ0eVgzQmhkRjl0TFhoR05EUm5VakZpTjB4VU1UZExjMnh0ZDJkdFVIVktaRVU9In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: aws-cicd
type: kubernetes.io/dockerconfigjson
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cicd-deployment
  namespace: aws-cicd
  labels:
    app: aws-cicd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aws-cicd-app
  template:
    metadata:
      labels:
        app: aws-cicd-app
    spec:
      containers:
      - name: aws-cicd-container
        image: devopsedu/employee
        ports:
        - containerPort: 8888
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: aws-cicd-np-service
  namespace: aws-cicd
  labels:
    app: aws-cicd-app
spec:
  selector:
    app: aws-cicd-app

  type: NodePort
  ports:
  - nodePort: 31029
    port: 8888
    targetPort: 8888
